[package]
name = "ublox"
version = "0.2.1"
authors = ["Lane Kolbly <lane@rscheme.org>"]
edition = "2018"
license = "MIT"
description = "A crate to communicate with u-blox GPS devices using the UBX protocol"
repository = "https://github.com/lkolbly/ublox"
readme = "../README.md"

[features]
default = ["std"]
std = []
serial = ["serialport", "crc"]

[dependencies]
chrono = { version = "0.4.19", default-features = false, features = [] }
serialport = { version = "3.3.0", optional = true, default-features = false, features = [] }
crc = { version = "1.8.1", optional = true }
bitflags = "1.2.1"
ublox_derive = { path = "../ublox_derive", version = "0.0.1" }
num-traits = { version = "0.2.12", default-features = false }

[build-dependencies]

[dev-dependencies]
rand = "0.7.3"
cpu-time = "1.0.0"
